image:
  repository: ghcr.io/yxwuxuanl/kube-cron-restarter
  tag: main
  imagePullPolicy: Always

deployment: true

daemonset: true

statefulset: true

nodeSelector: { }

tolerations: [ ]

timezone: Asia/Shanghai

extraArgs: [ ]

resources:
  requests:
    cpu: '20m'
    memory: 50Mi
  limits:
    cpu: '100m'
    memory: 100Mi